### ISSUE TITLE
Feature request: Add comments explaining what each setting does, or at least reference to manual

### ISSUE THREAD

**Issue by Delanii** [aartaka/nyxt-config#1]
I know this would be great undertaking, but adding helpfull comments into your config (which seems to be only one easy-to-find config, even featued in youtube) would mean a lot for anybody trying to configure nyxt; at least from the side f theming (colors, dark mode).
I think the default grey-ish setting will be one of the first things sought-out to change.
Thank you in advance for considering that.

**Comment by aartaka** [comment]
Ohhhh, sorry, I've just noticed your comment!

Yes, that is a fair point. I'll do that.

**Comment by aartaka** [comment]
Done in 13fa1dea0b1cfb1b8fb6dff6ce55b8bfdd974804. Sorry for such a long wait :cold_sweat:

**Comment by Delanii** [comment]
Thank you very much for doing that. It had put some light on things I wasnt sure of. Hoowever, when I tryed to change keybinds (I have vi-mode enabled, so it should have been for vi-scheme) I get error that there is no such scheme in keybindings package. What could I have done wrong?

**Comment by aartaka** [comment]
Oh wait, it's `scheme:vi-normal` 0_o

I'll fix it, thank for flagging the issue!

**Comment by Delanii** [comment]
Yep, that works ... Well, maybe this has connection to vi-states (normal, insert, visual, etc ... )?
Thank you for looking into that in such a short notice! Where did you find that? Somewhere in API documentation?

**Comment by aartaka** [comment]
I know a source and looked it up in [`/path/to/nyxt/libraries/keymap/scheme-names.lisp`](https://github.com/atlas-engineer/nyxt/blob/c4450043fedb9975db0d60a9e62fadd411314185/libraries/keymap/scheme-names.lisp#L8), but `:` `describe-any` `scheme:vi-` works equivalently fast :)

**Comment by Delanii** [comment]
OK, I am actually not sure where are nyxt libraries located, but I tried `describe-any` function interactively, but I am not getting any (sensible) results when looking for `scheme:vi-`. I get info that there are 611 variables, but when I try to look through the results, I am not seeing anything connected to keybindings.

Maybe I should read again manual to get better hold of what is going on ...

**Comment by aartaka** [comment]
> OK, I am actually not sure where are nyxt libraries located, but I tried `describe-any` function interactively, but I am not getting any (sensible) results when looking for `scheme:vi-`. I get info that there are 611 variables, but when I try to look through the results, I am not seeing anything connected to keybindings.
> 
> Maybe I should read again manual to get better hold of what is going on ...

That is weird. It may be that my image is totally different, as I'm mainly using Nyxt on some feature branches (notably `web-extensions` one), and those may have a different set of features.

**Comment by aartaka** [comment]
But yeah, manual has lots of useful stuff :)
