### ISSUE TITLE
Dynamic default-modes?

### ISSUE THREAD

**Issue by hendursaga** [aartaka/nyxt-config#2]
In the docstring for `*web-buffer-modes*`, it mentions "one can only set `default-modes' once, so I need to dynamically construct a list of modes and configure the slot only after it's done." Is this still the case now? Should it be considered a Nyxt bug (or a feature!)? Are there other ways of doing this?

**Comment by aartaka** [comment]
`default-modes` is not a slot, which makes it hard to configure in a composable/dynamic way :(

It's not a bug, it's a mere limitation of `default-modes` being a mere method with no memory section to back it up. Making it a slot wouldn't make much sense too.

Even though this design is definitely quite opaque, I'm not sure what to do with it other than collecting modes elsewhere (`*web-buffer-modes*`) and configuring them once only.
