### ISSUE TITLE
asd file

### ISSUE THREAD

**Issue by jgarte** [aartaka/nyxt-config#3]
Hi,

could this config benefit from a .asd file?

So, then, it can be easily packaged with Guix?

**Comment by aartaka** [comment]
Hmmmmm. I don't see much use in .asd file for this particular case, as Nyxt already provides a lot of ASDF-esque mechanisms for file/dependency management. But the point about Guix package does make sense. I'll add an .asd file.

**Comment by jgarte** [comment]
Cool, thanks! Let me know when the asd file is added and I'll package your config for Guix 'R Us: https://whereis.みんな/

It would be nice to have a ready made config like yours as a package :)

**Comment by aartaka** [comment]
@jgarte, I hope 84c3a7750e2cf343998351be5af22af11c47bc73 will be enough :)
